name: mad
description: MAD是一个开源的高精度 MPEG 音频解码库，支持 MPEG-1（Layer I, Layer II 和 LayerIII（也就是 MP3))
keywords:
  - mp3
  - audio decoder
  - media
author:
  name: jingzhishen
  email: jingzhishen@126.com
license: GPL

depends:                                       # 该组件依赖其他的组件
  - minilibc

build_config:
  include:
    - include
  cflag: ''                             # C 编译器所需要要的编译参数
  cxxflag: ''                         # CXX 编译器所需要要的编译参数
  asmflag: ''                            # 汇编器所需要要参数
  define:                                      # 宏定义
    - HAVE_CONFIG_H
    - FPM_DEFAULT

source_file:
  - "src/bit.c"
  - "src/decoder.c"
  - "src/fixed.c"
  - "src/frame.c"
  - "src/huffman.c"
  - "src/layer12.c"
  - "src/layer3.c"
  - "src/stream.c"
  - "src/synth.c"
  - "src/timer.c"
  - "src/version.c"

install:
  - dest: "include/"
    source:
      - include/mad.h
